name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        ruby-version: ['3.2.9', '3.3.9', '3.4.7']
        include:
          - ruby-version: '3.4.7'
            upload-coverage: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Show ruby version
        run: ruby -v

      - name: Run tests
        run: bundle exec rspec

      - name: Run lint
        run: bundle exec rubocop

      - name: Upload coverage reports to Codecov
        if: matrix.upload-coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/.resultset.json
          token: ${{ secrets.CODECOV_TOKEN }}
